// ─── Mock Data for Storefront ────────────────────────────────
// This provides realistic demo data before the backend API is connected.

import type {
  Product,
  Category,
  GoldRate,
  Banner,
  Review,
  Order,
  Address,
  LoyaltyInfo,
  Scheme,
  WishlistItem,
} from "./types";
import { placeholderImage } from "./utils";

// ─── Gold Rates ──────────────────────────────────────────────

export const mockGoldRates: GoldRate[] = [
  {
    metalType: "GOLD",
    purity: 999,
    ratePerGram: 7285,
    change24h: 45,
    changePercent24h: 0.62,
    updatedAt: new Date().toISOString(),
    currencyCode: "INR",
  },
  {
    metalType: "GOLD",
    purity: 916,
    ratePerGram: 6673,
    change24h: 38,
    changePercent24h: 0.57,
    updatedAt: new Date().toISOString(),
    currencyCode: "INR",
  },
  {
    metalType: "GOLD",
    purity: 750,
    ratePerGram: 5464,
    change24h: 32,
    changePercent24h: 0.59,
    updatedAt: new Date().toISOString(),
    currencyCode: "INR",
  },
  {
    metalType: "SILVER",
    purity: 999,
    ratePerGram: 89,
    change24h: -1.2,
    changePercent24h: -1.33,
    updatedAt: new Date().toISOString(),
    currencyCode: "INR",
  },
  {
    metalType: "PLATINUM",
    purity: 950,
    ratePerGram: 3150,
    change24h: 15,
    changePercent24h: 0.48,
    updatedAt: new Date().toISOString(),
    currencyCode: "INR",
  },
];

// ─── Categories ──────────────────────────────────────────────

export const mockCategories: Category[] = [
  { id: "cat-1", name: "Rings", slug: "rings", description: "Exquisite rings for every occasion", image: placeholderImage(400, 400, "Rings"), productCount: 245 },
  { id: "cat-2", name: "Necklaces", slug: "necklaces", description: "Stunning necklaces and chains", image: placeholderImage(400, 400, "Necklaces"), productCount: 189 },
  { id: "cat-3", name: "Earrings", slug: "earrings", description: "Beautiful earrings collection", image: placeholderImage(400, 400, "Earrings"), productCount: 312 },
  { id: "cat-4", name: "Bangles", slug: "bangles", description: "Traditional and modern bangles", image: placeholderImage(400, 400, "Bangles"), productCount: 167 },
  { id: "cat-5", name: "Bracelets", slug: "bracelets", description: "Elegant bracelets", image: placeholderImage(400, 400, "Bracelets"), productCount: 98 },
  { id: "cat-6", name: "Pendants", slug: "pendants", description: "Charming pendants", image: placeholderImage(400, 400, "Pendants"), productCount: 156 },
  { id: "cat-7", name: "Mangalsutra", slug: "mangalsutra", description: "Sacred mangalsutra collection", image: placeholderImage(400, 400, "Mangalsutra"), productCount: 78 },
  { id: "cat-8", name: "Chains", slug: "chains", description: "Gold and silver chains", image: placeholderImage(400, 400, "Chains"), productCount: 134 },
  { id: "cat-9", name: "Nose Pins", slug: "nose-pins", description: "Delicate nose pins", image: placeholderImage(400, 400, "Nose Pins"), productCount: 67 },
  { id: "cat-10", name: "Anklets", slug: "anklets", description: "Traditional anklets", image: placeholderImage(400, 400, "Anklets"), productCount: 45 },
];

// ─── Products ────────────────────────────────────────────────

function makeProduct(overrides: Partial<Product> & { id: string; name: string }): Product {
  const slug = overrides.name.toLowerCase().replace(/\s+/g, "-").replace(/[^a-z0-9-]/g, "");
  return {
    slug,
    sku: `CF-${overrides.id.slice(-4).toUpperCase()}`,
    description: overrides.description ?? `Beautiful ${overrides.name} crafted with precision and care. Each piece is hallmarked and certified for purity.`,
    shortDescription: overrides.shortDescription ?? `Elegant ${overrides.name} in fine craftsmanship`,
    categoryId: overrides.categoryId ?? "cat-1",
    categoryName: overrides.categoryName ?? "Rings",
    categorySlug: overrides.categorySlug ?? "rings",
    metalType: overrides.metalType ?? "GOLD",
    purity: overrides.purity ?? 916,
    purityLabel: overrides.purityLabel ?? "22K",
    grossWeightGrams: overrides.grossWeightGrams ?? 5.2,
    netWeightGrams: overrides.netWeightGrams ?? 4.8,
    images: overrides.images ?? [
      { id: "img-1", url: placeholderImage(600, 600, overrides.name), alt: overrides.name, isPrimary: true, sortOrder: 0 },
      { id: "img-2", url: placeholderImage(600, 600, `${overrides.name} - 2`), alt: `${overrides.name} angle 2`, isPrimary: false, sortOrder: 1 },
      { id: "img-3", url: placeholderImage(600, 600, `${overrides.name} - 3`), alt: `${overrides.name} angle 3`, isPrimary: false, sortOrder: 2 },
      { id: "img-4", url: placeholderImage(600, 600, `${overrides.name} - Detail`), alt: `${overrides.name} detail`, isPrimary: false, sortOrder: 3 },
    ],
    metalRatePerGram: overrides.metalRatePerGram ?? 6673,
    makingChargesPerGram: overrides.makingChargesPerGram ?? 800,
    makingChargesType: overrides.makingChargesType ?? "per_gram",
    makingChargesValue: overrides.makingChargesValue ?? 800,
    stoneDetails: overrides.stoneDetails ?? [],
    stoneTotalPrice: overrides.stoneTotalPrice ?? 0,
    huidNumber: overrides.huidNumber,
    gender: overrides.gender ?? "women",
    occasion: overrides.occasion ?? ["daily-wear"],
    tags: overrides.tags ?? [],
    isAvailable: overrides.isAvailable ?? true,
    isBestseller: overrides.isBestseller ?? false,
    isNew: overrides.isNew ?? false,
    isTrending: overrides.isTrending ?? false,
    sizes: overrides.sizes,
    specifications: overrides.specifications ?? {},
    rating: overrides.rating ?? 4.3,
    reviewCount: overrides.reviewCount ?? 24,
    currencyCode: "INR",
    ...overrides,
  };
}

export const mockProducts: Product[] = [
  makeProduct({
    id: "prod-001",
    name: "Celestial Solitaire Ring",
    categoryId: "cat-1",
    categoryName: "Rings",
    categorySlug: "rings",
    metalType: "GOLD",
    purity: 750,
    purityLabel: "18K",
    grossWeightGrams: 3.8,
    netWeightGrams: 3.2,
    metalRatePerGram: 5464,
    makingChargesValue: 1200,
    stoneDetails: [{ type: "Diamond", shape: "Round", weightCarat: 0.5, count: 1, clarity: "VS1", color: "F", cut: "Excellent", certification: "IGI", price: 45000 }],
    stoneTotalPrice: 45000,
    huidNumber: "ABCD1234EF",
    gender: "women",
    occasion: ["engagement", "party"],
    isBestseller: true,
    isTrending: true,
    rating: 4.8,
    reviewCount: 156,
    sizes: [
      { id: "s-6", label: "6", value: "6", isAvailable: true },
      { id: "s-7", label: "7", value: "7", isAvailable: true },
      { id: "s-8", label: "8", value: "8", isAvailable: true },
      { id: "s-9", label: "9", value: "9", isAvailable: false },
      { id: "s-10", label: "10", value: "10", isAvailable: true },
    ],
    specifications: { "Diamond Shape": "Round Brilliant", "Diamond Weight": "0.50 ct", "Diamond Clarity": "VS1", "Diamond Color": "F", Certification: "IGI Certified", "Band Width": "2.5mm" },
  }),
  makeProduct({
    id: "prod-002",
    name: "Royal Heritage Necklace",
    categoryId: "cat-2",
    categoryName: "Necklaces",
    categorySlug: "necklaces",
    grossWeightGrams: 25.5,
    netWeightGrams: 24.0,
    makingChargesValue: 600,
    huidNumber: "EFGH5678IJ",
    occasion: ["wedding", "festive"],
    isBestseller: true,
    rating: 4.9,
    reviewCount: 89,
    specifications: { Length: "18 inches", "Clasp Type": "Lobster Claw", Finish: "High Polish", Pattern: "Temple Design" },
  }),
  makeProduct({
    id: "prod-003",
    name: "Floral Jhumka Earrings",
    categoryId: "cat-3",
    categoryName: "Earrings",
    categorySlug: "earrings",
    grossWeightGrams: 12.0,
    netWeightGrams: 11.5,
    makingChargesValue: 750,
    huidNumber: "IJKL9012MN",
    occasion: ["festive", "wedding"],
    isNew: true,
    isTrending: true,
    rating: 4.6,
    reviewCount: 67,
    specifications: { Style: "Jhumka", "Drop Length": "3.5cm", "Back Type": "Push Back", Finish: "Antique Gold" },
  }),
  makeProduct({
    id: "prod-004",
    name: "Twisted Rope Bangle",
    categoryId: "cat-4",
    categoryName: "Bangles",
    categorySlug: "bangles",
    grossWeightGrams: 18.0,
    netWeightGrams: 18.0,
    makingChargesValue: 500,
    huidNumber: "MNOP3456QR",
    occasion: ["daily-wear"],
    rating: 4.4,
    reviewCount: 43,
    specifications: { Style: "Rope Twist", "Inner Diameter": "65mm", Width: "4mm", Finish: "Satin" },
  }),
  makeProduct({
    id: "prod-005",
    name: "Diamond Cluster Pendant",
    categoryId: "cat-6",
    categoryName: "Pendants",
    categorySlug: "pendants",
    metalType: "GOLD",
    purity: 750,
    purityLabel: "18K",
    grossWeightGrams: 4.2,
    netWeightGrams: 3.5,
    metalRatePerGram: 5464,
    makingChargesValue: 1000,
    stoneDetails: [{ type: "Diamond", shape: "Round", weightCarat: 0.3, count: 7, clarity: "SI1", color: "G", cut: "Very Good", certification: "IGI", price: 28000 }],
    stoneTotalPrice: 28000,
    gender: "women",
    occasion: ["party", "office-wear"],
    isNew: true,
    rating: 4.7,
    reviewCount: 34,
    specifications: { "Diamond Total Weight": "0.30 ct", Diamonds: "7 Round Brilliant", Setting: "Prong", "Chain Included": "Yes - 16 inch" },
  }),
  makeProduct({
    id: "prod-006",
    name: "Classic Cuban Chain",
    categoryId: "cat-8",
    categoryName: "Chains",
    categorySlug: "chains",
    grossWeightGrams: 20.0,
    netWeightGrams: 20.0,
    makingChargesValue: 450,
    gender: "men",
    occasion: ["daily-wear"],
    isTrending: true,
    rating: 4.5,
    reviewCount: 112,
    specifications: { Style: "Cuban Link", Length: "22 inches", Width: "4mm", "Clasp Type": "Box Clasp" },
  }),
  makeProduct({
    id: "prod-007",
    name: "Bridal Kundan Set",
    categoryId: "cat-2",
    categoryName: "Necklaces",
    categorySlug: "necklaces",
    metalType: "KUNDAN",
    purity: 916,
    purityLabel: "22K",
    grossWeightGrams: 85.0,
    netWeightGrams: 65.0,
    makingChargesValue: 900,
    stoneDetails: [
      { type: "Kundan", shape: "Various", weightCarat: 15.0, count: 40, price: 35000 },
      { type: "Pearl", shape: "Round", weightCarat: 5.0, count: 20, price: 8000 },
    ],
    stoneTotalPrice: 43000,
    occasion: ["wedding"],
    isBestseller: true,
    rating: 4.9,
    reviewCount: 45,
    specifications: { "Set Includes": "Necklace + Earrings + Maang Tikka", Style: "Traditional Kundan", "Stone Type": "Kundan & Pearls", Finish: "Polki" },
  }),
  makeProduct({
    id: "prod-008",
    name: "Platinum Love Band",
    categoryId: "cat-1",
    categoryName: "Rings",
    categorySlug: "rings",
    metalType: "PLATINUM",
    purity: 950,
    purityLabel: "Pt950",
    grossWeightGrams: 6.5,
    netWeightGrams: 6.5,
    metalRatePerGram: 3150,
    makingChargesValue: 1500,
    gender: "unisex",
    occasion: ["engagement", "daily-wear"],
    isNew: true,
    rating: 4.7,
    reviewCount: 28,
    sizes: [
      { id: "s-6", label: "6", value: "6", isAvailable: true },
      { id: "s-7", label: "7", value: "7", isAvailable: true },
      { id: "s-8", label: "8", value: "8", isAvailable: true },
      { id: "s-9", label: "9", value: "9", isAvailable: true },
      { id: "s-10", label: "10", value: "10", isAvailable: true },
      { id: "s-11", label: "11", value: "11", isAvailable: true },
      { id: "s-12", label: "12", value: "12", isAvailable: true },
    ],
    specifications: { Metal: "Platinum 950", "Band Width": "5mm", Finish: "Matte Center, Polished Edges", Comfort: "Comfort Fit" },
  }),
  makeProduct({
    id: "prod-009",
    name: "Silver Anklet Pair",
    categoryId: "cat-10",
    categoryName: "Anklets",
    categorySlug: "anklets",
    metalType: "SILVER",
    purity: 925,
    purityLabel: "925 Sterling",
    grossWeightGrams: 30.0,
    netWeightGrams: 30.0,
    metalRatePerGram: 89,
    makingChargesValue: 200,
    gender: "women",
    occasion: ["daily-wear", "festive"],
    rating: 4.2,
    reviewCount: 56,
    specifications: { Style: "Ghungroo", Length: "10 inches each", "Sold As": "Pair", Bells: "12 per anklet" },
  }),
  makeProduct({
    id: "prod-010",
    name: "Emerald Tennis Bracelet",
    categoryId: "cat-5",
    categoryName: "Bracelets",
    categorySlug: "bracelets",
    metalType: "GOLD",
    purity: 750,
    purityLabel: "18K",
    grossWeightGrams: 14.5,
    netWeightGrams: 10.0,
    metalRatePerGram: 5464,
    makingChargesValue: 1100,
    stoneDetails: [
      { type: "Emerald", shape: "Oval", weightCarat: 3.5, count: 15, clarity: "AA", price: 52000 },
      { type: "Diamond", shape: "Round", weightCarat: 0.8, count: 30, clarity: "VS2", color: "G", cut: "Excellent", price: 35000 },
    ],
    stoneTotalPrice: 87000,
    gender: "women",
    occasion: ["party", "engagement"],
    isTrending: true,
    isNew: true,
    rating: 4.8,
    reviewCount: 19,
    specifications: { "Emerald Weight": "3.5 ct total", "Diamond Weight": "0.80 ct total", Length: "7 inches", Clasp: "Hidden Box Clasp with Safety" },
  }),
  makeProduct({
    id: "prod-011",
    name: "Temple Gold Mangalsutra",
    categoryId: "cat-7",
    categoryName: "Mangalsutra",
    categorySlug: "mangalsutra",
    grossWeightGrams: 15.0,
    netWeightGrams: 14.5,
    makingChargesValue: 700,
    huidNumber: "QRST7890UV",
    occasion: ["wedding", "daily-wear"],
    isBestseller: true,
    rating: 4.6,
    reviewCount: 78,
    specifications: { Length: "24 inches", "Black Beads": "Double line", Pendant: "Temple motif", Chain: "Box chain with black beads" },
  }),
  makeProduct({
    id: "prod-012",
    name: "Delicate Nose Pin",
    categoryId: "cat-9",
    categoryName: "Nose Pins",
    categorySlug: "nose-pins",
    metalType: "GOLD",
    purity: 750,
    purityLabel: "18K",
    grossWeightGrams: 0.8,
    netWeightGrams: 0.5,
    metalRatePerGram: 5464,
    makingChargesValue: 500,
    makingChargesType: "flat",
    stoneDetails: [{ type: "Diamond", shape: "Round", weightCarat: 0.05, count: 1, clarity: "VS1", color: "E", cut: "Excellent", certification: "IGI", price: 3500 }],
    stoneTotalPrice: 3500,
    gender: "women",
    occasion: ["daily-wear", "office-wear"],
    rating: 4.4,
    reviewCount: 92,
    specifications: { "Diamond Weight": "0.05 ct", Style: "Wire / Screw", "Pin Length": "8mm" },
  }),
];

// ─── Banners ─────────────────────────────────────────────────

export const mockBanners: Banner[] = [
  {
    id: "banner-1",
    title: "Bridal Collection 2026",
    subtitle: "Handcrafted masterpieces for your special day. Explore our exclusive wedding jewelry.",
    ctaText: "Shop Bridal",
    ctaLink: "/category/necklaces?occasion=wedding",
    imageUrl: placeholderImage(1200, 500, "Bridal Collection"),
    bgColor: "from-navy to-navy-light",
  },
  {
    id: "banner-2",
    title: "Akshaya Tritiya Special",
    subtitle: "Flat 20% off on making charges. Buy gold on the most auspicious day.",
    ctaText: "Shop Now",
    ctaLink: "/category/rings",
    imageUrl: placeholderImage(1200, 500, "Akshaya Tritiya"),
    bgColor: "from-gold-dark to-gold",
  },
  {
    id: "banner-3",
    title: "Diamond Essentials",
    subtitle: "Certified diamonds starting at Rs 15,000. Every piece tells a story.",
    ctaText: "Explore Diamonds",
    ctaLink: "/category/pendants?metal=DIAMOND",
    imageUrl: placeholderImage(1200, 500, "Diamond Collection"),
    bgColor: "from-navy-dark to-navy",
  },
];

// ─── Reviews ─────────────────────────────────────────────────

export const mockReviews: Review[] = [
  {
    id: "rev-1",
    userId: "user-1",
    userName: "Priya S.",
    rating: 5,
    title: "Absolutely stunning!",
    comment: "The craftsmanship is impeccable. My ring looks even better in person than in the photos. The diamond sparkles beautifully. Received in premium packaging with all certificates. Worth every rupee!",
    images: [],
    isVerifiedPurchase: true,
    createdAt: "2026-03-15T10:30:00Z",
    helpfulCount: 23,
  },
  {
    id: "rev-2",
    userId: "user-2",
    userName: "Rahul M.",
    rating: 4,
    title: "Great quality, slightly heavy",
    comment: "Beautiful piece with excellent finish. The gold purity is exactly as described. Only reason for 4 stars is it feels slightly heavier than expected, but that is actually a good sign of quality.",
    images: [],
    isVerifiedPurchase: true,
    createdAt: "2026-03-10T14:20:00Z",
    helpfulCount: 12,
  },
  {
    id: "rev-3",
    userId: "user-3",
    userName: "Anjali K.",
    rating: 5,
    title: "Perfect engagement ring",
    comment: "My fiance proposed with this ring and I could not be happier! The diamond is eye-clean and has amazing brilliance. The setting is secure. Highly recommend for engagement rings.",
    images: [],
    isVerifiedPurchase: true,
    createdAt: "2026-02-28T09:15:00Z",
    helpfulCount: 45,
  },
  {
    id: "rev-4",
    userId: "user-4",
    userName: "Deepak R.",
    rating: 4,
    title: "Elegant daily wear",
    comment: "Bought this for my wife's birthday. She wears it every day and it still looks brand new after 2 months. Good quality gold with proper hallmark.",
    images: [],
    isVerifiedPurchase: true,
    createdAt: "2026-02-20T16:45:00Z",
    helpfulCount: 8,
  },
  {
    id: "rev-5",
    userId: "user-5",
    userName: "Meera P.",
    rating: 5,
    title: "Best online jewelry purchase",
    comment: "I was hesitant to buy jewelry online but CaratFlow exceeded my expectations. The product matches the description perfectly. Fast delivery with tamper-proof packaging. Will buy again!",
    images: [],
    isVerifiedPurchase: true,
    createdAt: "2026-02-14T11:00:00Z",
    helpfulCount: 31,
  },
];

// ─── Addresses ───────────────────────────────────────────────

export const mockAddresses: Address[] = [
  {
    id: "addr-1",
    label: "Home",
    fullName: "Priya Sharma",
    phone: "+91 98765 43210",
    addressLine1: "42, Lotus Apartments",
    addressLine2: "MG Road, Bandra West",
    city: "Mumbai",
    state: "Maharashtra",
    pincode: "400050",
    country: "India",
    isDefault: true,
  },
  {
    id: "addr-2",
    label: "Office",
    fullName: "Priya Sharma",
    phone: "+91 98765 43210",
    addressLine1: "Tech Park, Building C, 4th Floor",
    addressLine2: "Andheri East",
    city: "Mumbai",
    state: "Maharashtra",
    pincode: "400069",
    country: "India",
    isDefault: false,
  },
];

// ─── Orders ──────────────────────────────────────────────────

export const mockOrders: Order[] = [
  {
    id: "order-001",
    orderNumber: "CF-2026-0001",
    status: "delivered",
    items: [
      {
        id: "oi-1",
        product: mockProducts[0]!,
        quantity: 1,
        selectedSize: "7",
        pricePaise: 6789200,
        metalRateAtPurchase: 5464,
      },
    ],
    shippingAddress: mockAddresses[0]!,
    subtotalPaise: 6789200,
    discountPaise: 0,
    taxPaise: 203676,
    cgstPaise: 101838,
    sgstPaise: 101838,
    igstPaise: 0,
    shippingPaise: 0,
    totalPaise: 6992876,
    paymentMethod: "razorpay",
    paymentStatus: "paid",
    trackingNumber: "DTDC123456789",
    trackingUrl: "https://tracking.example.com/DTDC123456789",
    timeline: [
      { status: "placed", timestamp: "2026-03-01T10:00:00Z", description: "Order placed successfully" },
      { status: "confirmed", timestamp: "2026-03-01T10:05:00Z", description: "Order confirmed and payment received" },
      { status: "processing", timestamp: "2026-03-02T09:00:00Z", description: "Order is being prepared" },
      { status: "shipped", timestamp: "2026-03-03T14:00:00Z", description: "Shipped via DTDC Express" },
      { status: "out_for_delivery", timestamp: "2026-03-05T08:00:00Z", description: "Out for delivery" },
      { status: "delivered", timestamp: "2026-03-05T14:30:00Z", description: "Delivered successfully" },
    ],
    createdAt: "2026-03-01T10:00:00Z",
    updatedAt: "2026-03-05T14:30:00Z",
    invoiceUrl: "/invoices/CF-2026-0001.pdf",
  },
  {
    id: "order-002",
    orderNumber: "CF-2026-0002",
    status: "shipped",
    items: [
      {
        id: "oi-2",
        product: mockProducts[2]!,
        quantity: 1,
        pricePaise: 8542500,
        metalRateAtPurchase: 6673,
      },
    ],
    shippingAddress: mockAddresses[0]!,
    subtotalPaise: 8542500,
    discountPaise: 250000,
    taxPaise: 248775,
    cgstPaise: 124388,
    sgstPaise: 124387,
    igstPaise: 0,
    shippingPaise: 0,
    totalPaise: 8541275,
    couponCode: "WELCOME10",
    paymentMethod: "upi",
    paymentStatus: "paid",
    trackingNumber: "BW987654321",
    timeline: [
      { status: "placed", timestamp: "2026-03-28T15:00:00Z", description: "Order placed successfully" },
      { status: "confirmed", timestamp: "2026-03-28T15:10:00Z", description: "Order confirmed" },
      { status: "processing", timestamp: "2026-03-29T10:00:00Z", description: "Order is being prepared" },
      { status: "shipped", timestamp: "2026-03-31T11:00:00Z", description: "Shipped via BlueDart" },
    ],
    createdAt: "2026-03-28T15:00:00Z",
    updatedAt: "2026-03-31T11:00:00Z",
    estimatedDelivery: "2026-04-05",
  },
];

// ─── Loyalty ─────────────────────────────────────────────────

export const mockLoyalty: LoyaltyInfo = {
  points: 12450,
  tier: "silver",
  tierProgress: 83,
  nextTier: "Gold",
  pointsToNextTier: 2550,
  history: [
    { id: "lt-1", type: "earned", points: 1400, description: "Purchase: CF-2026-0001", date: "2026-03-05T14:30:00Z", orderId: "order-001" },
    { id: "lt-2", type: "earned", points: 1700, description: "Purchase: CF-2026-0002", date: "2026-03-28T15:00:00Z", orderId: "order-002" },
    { id: "lt-3", type: "earned", points: 500, description: "Birthday Bonus", date: "2026-01-15T00:00:00Z" },
    { id: "lt-4", type: "redeemed", points: -1000, description: "Redeemed for discount", date: "2026-02-10T12:00:00Z" },
    { id: "lt-5", type: "earned", points: 200, description: "Referral bonus - Anita K.", date: "2026-02-01T10:00:00Z" },
  ],
};

// ─── Schemes ─────────────────────────────────────────────────

export const mockSchemes: Scheme[] = [
  {
    id: "scheme-001",
    name: "Golden Harvest Plan",
    type: "gold_savings",
    monthlyAmountPaise: 500000,
    totalMonths: 11,
    paidMonths: 7,
    totalPaidPaise: 3500000,
    maturityAmountPaise: 6000000,
    bonusMonths: 1,
    startDate: "2025-09-01",
    maturityDate: "2026-08-01",
    status: "active",
    installments: Array.from({ length: 11 }, (_, i) => ({
      month: i + 1,
      dueDate: `2025-${String(9 + i > 12 ? 9 + i - 12 : 9 + i).padStart(2, "0")}-01`,
      amountPaise: 500000,
      status: i < 7 ? "paid" as const : i === 7 ? "due" as const : "upcoming" as const,
      paidDate: i < 7 ? `2025-${String(9 + i > 12 ? 9 + i - 12 : 9 + i).padStart(2, "0")}-01` : undefined,
    })),
  },
];

// ─── Wishlist ────────────────────────────────────────────────

export const mockWishlistItems: WishlistItem[] = [
  { id: "wl-1", product: mockProducts[0]!, addedAt: "2026-03-20T10:00:00Z", priceAlertEnabled: true, priceAlertThreshold: 60000 },
  { id: "wl-2", product: mockProducts[4]!, addedAt: "2026-03-18T15:30:00Z", priceAlertEnabled: false },
  { id: "wl-3", product: mockProducts[9]!, addedAt: "2026-03-15T09:00:00Z", priceAlertEnabled: true, priceAlertThreshold: 120000 },
];
